[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/wa-webhook"
  status = 200

[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/wa-dashboard-data"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
